export const QUEUE_NAMES = {
  ORDER_QUEUE: 'ORDER_QUEUE',
  INVENTORY_QUEUE: 'INVENTORY_QUEUE',
  ANALYTICS_QUEUE: 'ANALYTICS_QUEUE',
  NOTIFICATION_QUEUE: 'NOTIFICATION_QUEUE',
  EMAIL_QUEUE: 'EMAIL_QUEUE',
  PDF_QUEUE: 'PDF_QUEUE',
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];

